install.packages("ggplot2", dependencies=TRUE)
install.packages("plyr")
install.packages("ggthemes")
install.packages("reshape2")

library("ggplot2")
library("plyr")
library("ggthemes")
library("reshape2")

head(iris)
iris[1:2, ]
df <- melt(iris, id.vars = "Species")
df[1:2, ]
myplot <- ggplot(data = iris, aes(x = Sepal.Length, y = Sepal.Width))
summary(myplot)
ggplot(data = iris, aes(x = Sepal.Length, y = Sepal.Width)) + geom_point()
ggplot(data = iris, aes(x = Sepal.Length, y = Sepal.Width, color = Species)) + geom_point(aes(shape = Species, sizes = 3)

head(diamonds)
d2 <- diamonds[sample(1:dim(diamonds)[1], 1000), ]
summary(d2)
myplot <- ggplot(data = d2, aes(x = carat, y = price, color = color)) + geom_point (size = 3)
library(MASS)
ggplot(birthwt, aes(factor(race), bwt)) + geom_boxplot()
myplot <- ggplot(birthwt, aes(factor(race), bwt)) + geom_boxplot()
summary(myplot)
ggplot(iris, aes(Sepal.Length, Sepal.Width, color = Species)) + geom_point() + facet_grid(Species ~ .)
ggplot(iris, aes(Sepal.Length, Sepal.Width, color = Species)) + geom_point() + facet_grid(. ~ Species)
ggplot(iris, aes(Sepal.Length, Sepal.Width, color = Species)) + geom_point() + facet_wrap( ~ Species)
library(RColorBrewer)
display.brewer.all()
df <- melt(iris, id.vars = "Species")
ggplot(df, aes(Species, value, fill = variable)) + geom_bar(stat = "identity", position = "dodge") + scale_fill_brewer(palette = "Set1")
ggplot(birthwt, aes(factor(race), bwt)) + geom_boxplot(width = .2) + scale_y_continuous(labels = (paste0(1:4
summary(d2)
h <- ggplot(faithful, aes(x = waiting))
h + geom_histogram(binwidth = 30, color = "black")
h + geom_histogram(binwidth = 8, fill = "steelblue", color = "black")
ggplot(iris, aes(Species, Sepal.Length)) + geom_bar(stat = "identity")
ggplot(df, aes(Species, value, fill = variable)) + geom_bar(stat = "identity", position = "dodge", color ="black")
ggplot(data = d2, aes(clarity, fill = cut)) + geom_bar(position = "dodge")
ggplot(faithful, aes(waiting)) + geom_density(fill = "blue", alpha = 0.1)
ggplot(iris, aes(Sepal.Lenght, Sepal.Width, color = Species)) + geom_point(aes(shape = Species), size = 3) + geom_smooth(method = "lm")
ggplot(iris, aes(Sepal.Length, Sepal.Width, color = Species)) + geom_point(aes(shape = Species), size = 3) + geom_smooth(method = "lm")
install.packages(ggthemes)
library(ggthemes)
